version: '3'
virtualmachines:
- environment:
    TERM: xterm
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-6-05-10-2022-1
  machine_type: n1-standard-1
  name: rhel
  shell: /bin/bash
secrets:
- name: ACTIVATION_KEY